package Lexer;

public enum Tokens {
    reservadaCond,
    reservadaBlock,
    condicion2,
    instruccion2,
    instruccion1,
    cardinal,
    direccion,
    times,
    abrirdo,
    cerrardo,
    negacion,
    quieto,
    condicion1,
    igual,
    suma,
    resta,
    multiplicacion,
    division,
    corchetei,
    corcheted,
    parentesisi,
    parentesisd,
    pipeline,
    semicolon,
    comma,
    colon,
    inicio,
    var,
    funcion,
    identificador,
    numero,
    error
}