package Lexer;

public enum Tokens {
    reservadaCond,
    reservadaBlock,
    times,
    abrirdo,
    cerrardo,
    condicion,
    instruccion,
    igual,
    suma,
    resta,
    multiplicacion,
    division,
    corchetei,
    corcheted,
    parentesisi,
    parentesisd,
    pipeline,
    semicolon,
    coma,
    colon,
    inicio,
    var,
    funcion,
    identificador,
    numero,
    error
}